### ISSUE TITLE
Accessing secrets always fails to authorize credentials

### ISSUE THREAD

**Issue by vjp23** [googleapis/python-secret-manager#22]
I'm running a Flask app in a Docker container which uses Twilio to handle phone calls. My Twilio API id and auth token are stored in GCP Secret Manager.

I am using a GCP service account. The credentials JSON file is named in the GOOGLE_APPLICATION_CREDENTIALS environment variable, and I have confirmed that my Python app can find this variable, open the file at that path, and display the correct credential information from the JSON file.

I have confirmed that the credentials contained in the file match those displayed in the GCP console. My service account is both an owner of my GCP project and a Secret Manager Accessor.

Unfortunately, no matter what I try, I receive the following error:

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "Permission denied on resource project <MY GCP PROJECT NAME>."
        debug_error_string = "{"created":"@1588431508.906067585","description":"Error received from peer ipv4:172.217.12.202:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Permission denied on resource project <MY GCP PROJECT NAME>.","grpc_status":7}"
```

**Critically, using the gcloud CLI, this service account is able to successfully get these same secrets. Further, I am able to successfully push files into a GCS bucket with these credentials in the same Python app.**

#### Environment details

  - OS type and version: Docker container built FROM python:3.8.2-slim-buster, Same error on python:3.6.10-slim-buster
  - Python version: 3.8.2 and 3.6.10
  - `google-cloud-secret-manager` version: 0.2.0

#### Steps to reproduce

  1. Build a Dockerfile from python:3.8.2-slim-buster with JSON svc acct credentials in ENV
  2. Attempt to access a secret in the Secret Manager

#### Code example

**WORKS:**
```python
import urllib.request
from google.cloud import storage, secretmanager

def upload_wav_to_google_storage(source_url, save_as, bucket_name):   
    file = urllib.request.urlopen(source_url)

    storage_client = storage.Client()

    bucket = storage_client.get_bucket(bucket_name)
    blob = bucket.blob(save_as)

    blob.upload_from_string(file.read(), content_type='audio/wav')
```

**DOES NOT WORK:**
```python
def access_secret(project_id, secret_id, version):
    """
    Access a secret- API token, etc- stored in Secret Manager

    Code from https://cloud.google.com/secret-manager/docs/creating-and-accessing-secrets#secretmanager-access-secret-version-python
    """
    client = secretmanager.SecretManagerServiceClient()

    # Build the resource name of the secret version
    name = client.secret_version_path(project_id, secret_id, version)

    # Access the secret version
    response = client.access_secret_version(name)

    # Return the secret payload
    payload = response.payload.data.decode('UTF-8')
    
    return payload
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "Permission denied on resource project <MY GCP PROJECT NAME>."
        debug_error_string = "{"created":"@1588436335.061284036","description":"Error received from peer ipv4:172.217.11.10:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Permission denied on resource project <MY GCP PROJECT NAME>.","grpc_status":7}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from parameters import *
  File "/code/src/parameters.py", line 16, in <module>
    TWILIO_SID = access_secret(GCP_PROJECT, 'TWILIO_ACCOUNT_SID', os.environ['TWILIO_ACCOUNT_SID_VERSION'])
  File "/code/src/utils.py", line 46, in access_secret
    response = client.access_secret_version(name)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/secretmanager_v1/gapic/secret_manager_service_client.py", line 963, in access_secret_version
    return self._inner_api_calls["access_secret_version"](
  File "/usr/local/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.8/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.PermissionDenied: 403 Permission denied on resource project <MY GCP PROJECT NAME>.
```
where TWILIO_ACCOUNT_SID is the name of my secret in Secret Manager.

I have also tried to instantiate the client using the `from_service_account_file()` classmethod. This successfully creates a client instance, but again fails upon trying to get the secret.

I have tried this with multiple service accounts, all with the correct permissions set in the console. Any help here would be appreciated.

Thanks so much!!!

**Comment by vjp23** [comment]
Some additional information:

I've tried using this pattern:

1. Create new key JSON file in GCP Console

2.
```python
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file('/path/to/key/file.json')

client = secretmanager.SecretManagerServiceClient(credentials=credentials)

name = client.secret_version_path(project_id, secret_id, version)

response = client.access_secret_version(name)
```

This also fails. 

However, I note that if I try to `print(credentials.token)` I get a `None`. Similarly, if I try to `print(credentials.valid)` I get `False`. 

This is odd, since I literally just made and downloaded this key file about 5 minutes ago. Could this be related to the format of the JSON key file?

**Comment by vjp23** [comment]
OK, I was using the project name and not the project ID. That was the problem. Sorry for the interruption!
