### ISSUE TITLE
New release is incompatible with M1

### ISSUE THREAD

**Issue by av1m** [googleapis/python-secret-manager#288]
#### Environment details

  - OS type and version: `MacBook Air M1 : MacOS Monterey 12.2.1`
  - Python version: `Python 3.10.1`
  - pip version: `pip 22.0.4`
  - `google-cloud-secret-manager` version: `2.10.0`

#### Steps to reproduce

  1. Install the dependencies `google-cloud-secret-manager==2.10.0`
  2. Import the library

#### Code example

```python
from google.cloud.secretmanager import SecretManagerServiceClient
```

#### Stack trace
```
>>> from google.cloud.secretmanager import SecretManagerServiceClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/av1m/project/.venv/lib/python3.10/site-packages/google/cloud/secretmanager/__init__.py", line 17, in <module>
    from google.cloud.secretmanager_v1.services.secret_manager_service.client import (
  File "/Users/av1m/project/.venv/lib/python3.10/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/__init__.py", line 16, in <module>
    from .client import SecretManagerServiceClient
  File "/Users/av1m/project/.venv/lib/python3.10/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/client.py", line 24, in <module>
    from google.api_core import gapic_v1
  File "/Users/av1m/project/.venv/lib/python3.10/site-packages/google/api_core/gapic_v1/__init__.py", line 16, in <module>
    from google.api_core.gapic_v1 import config
  File "/Users/av1m/project/.venv/lib/python3.10/site-packages/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
  File "/Users/av1m/project/.venv/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/av1m/project/.venv/lib/python3.10/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/av1m/project/.venv/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): tried: '/Users/av1m/project/.venv/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cygrpc.cpython-310-darwin.so' (no such file), '/usr/lib/cygrpc.cpython-310-darwin.so' (no such file)
```

I try on Linux and i don't have this issue. In this sense, we can see the "incompatible architecture" in the traceback.

**Comment by av1m** [comment]
Ok it seem that the problem come from `grpc`.
I was able to solve this by running this
```bash
pip install --no-binary :all: grpcio --ignore-installed
pip install --no-binary :all: grpcio-tools --ignore-installed
````
[Source](https://github.com/grpc/grpc/issues/28387)
