### ISSUE TITLE
503 DNS resolution failed for service: secretmanager.googleapis.com:443

### ISSUE THREAD

**Issue by brpatel007** [googleapis/python-secret-manager#401]
#### Environment details

  - OS type and version: Ubuntu 22.04.1
  - Python version: 3.7.16
  - pip version: 22.0.4
  - `google-cloud-secret-manager` version: 2.7.2

#### Steps to reproduce

  1. Run the code given below

#### Code example

```python
from google.cloud import secretmanager
client = secretmanager.SecretManagerServiceClient()
name = f"projects/{project_id}/secrets/{secret_name}/versions/latest"
payload = client.access_secret_version(name=name).payload.data.decode("UTF-8")
print(payload)
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for service: secretmanager.googleapis.com:443"
	debug_error_string = "{"created":"@1677255939.419684061","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":1324,"referenced_errors":[{"created":"@1677255939.419665546","description":"DNS resolution failed for service: secretmanager.googleapis.com:443","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":359,"grpc_status":14,"referenced_errors":[{"created":"@1677255939.419472016","description":"C-ares status is not ARES_SUCCESS qtype=A name=secretmanager.googleapis.com is_balancer=0: Timeout while contacting DNS servers","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":698}]}]}"
>
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 188, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 DNS resolution failed for service: secretmanager.googleapis.com:443
```

I found a reference to the same error [here](https://github.com/grpc/grpc/issues/30462), so please check if it's the same issue.

**Comment by atulep** [comment]
How many times did you run this code? It looks like a temporary failure.

**Comment by parthea** [comment]
I'm not able to produce this error. 5XX errors are usually related to the backend and in some cases can be transient. I'm going to close this issue but please open a new issue if the problem re-appears and we can escalate to the API team.
