### ISSUE TITLE
SecretManagerServiceClient import error due to proto

### ISSUE THREAD

**Issue by ketozhang** [googleapis/python-secret-manager#52]
#### Environment details

  - OS type and version: Debian 10 Buster
  - Python version: 3.7.9
  - pip version: 20+
  - `google-cloud-secret-manager` version: 2.0.0

#### Steps to reproduce

Error produced when install my own package which the `setup.py` has `install_requires` as `'google-cloud-secret-manager>=2.0.0,<3.0.0`. Equivalently this runs

```sh
$ pip install 'google-cloud-secret-manager>=2.0.0,<3.0.0'
...
Downloading google_cloud_secret_manager-2.0.0-py2.py3-none-any.whl (88 kB)
...
Downloading proto-plus-1.10.2.tar.gz (42 kB)
```

#### Code example

```python
from google.cloud.secretmanager_v1 import SecretManagerServiceClient
```

#### Stack trace
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/REDACTED/common.py", line 10, in <module>
    from google.cloud.secretmanager_v1 import SecretManagerServiceClient
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/google/cloud/secretmanager_v1/__init__.py", line 18, in <module>
    from .services.secret_manager_service import SecretManagerServiceClient
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/__init__.py", line 18, in <module>
    from .client import SecretManagerServiceClient
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/client.py", line 35, in <module>
    from google.cloud.secretmanager_v1.services.secret_manager_service import pagers
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/pagers.py", line 20, in <module>
    from google.cloud.secretmanager_v1.types import resources
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/google/cloud/secretmanager_v1/types/__init__.py", line 18, in <module>
    from .resources import (
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/google/cloud/secretmanager_v1/types/resources.py", line 38, in <module>
    class Secret(proto.Message):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/proto/message.py", line 95, in __new__
    map_fields[msg_name] = MessageMeta(msg_name, (Message,), entry_attrs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/proto/message.py", line 215, in __new__
    field=[i.descriptor for i in fields],
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/proto/message.py", line 215, in <listcomp>
    field=[i.descriptor for i in fields],
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/proto/fields.py", line 111, in descriptor
    proto3_optional=self.optional,
ValueError: Protocol message FieldDescriptorProto has no "proto3_optional" field.
```

**Comment by busunkim96** [comment]
Hi @ketozhang,

Can you try upgrading your version of `protobuf`? proto3 optional was added somewhat recently.

**Comment by ketozhang** [comment]
Thanks @busunkim96 ,

I believe `protobuf` version is the key culprit. I was able to resolve it not by doing this but by removing strict versioning on `requirements.txt` for other Google Python libraries. Do other libraries require an older version of `protobuf`?

**Comment by busunkim96** [comment]
@ketozhang Apologies, going through a backlog of issues and just saw this one. 

google-cloud-* libraries are pinned in such a way that they only require progressively newer versions or `protobuf`. (https://github.com/googleapis/python-api-core/blob/6789e675814983cbd413dc045c11a7c7a176042c/setup.py#L33). If you notice two different Google maintained libraries seem to be requiring incompatible ranges, please file a bug!
